import { Language, getActiveLanguage } from './languages';

const translations: Record<Language, Record<string, string>> = {
  cs: {
    about: 'Jakékoliv připomínky či nápady neváhejte sdělit na:',
    affirmative: 'Afirmace',
    cancel: 'Zrušit',
    close: 'Zavřít',
    debatiadaA1ClosingLabel: 'A1 závěr',
    format: 'Formát debaty',
    formatChangeConfirm: 'Změna formátu resetuje stopky. Opravdu pokračovat?',
    formatDebatiada: 'Debatiáda',
    formatKpdp: 'KPDP',
    language: 'Jazyk',
    languageCs: 'Čeština',
    languageEn: 'English',
    linearFeatureDiscoveryButton: 'Klepněte na kartičku na začátku a konci každé řeči',
    linearFeatureDiscoverySettings: 'Rozložení můžete změnit v nastavení',
    linearPrepTimeSuffix: ' - přípravný čas',
    mode: 'Režim zobrazení',
    modeClassic: 'Klasický',
    modeLinear: 'Jednoduchý',
    negative: 'Negace',
    ok: 'Ano',
    pause: 'Pozastavit',
    preptime: 'Přípravný čas',
    pwaPromptIOSAddToHomescreen: 'Vyberte možnost Přidat na plochu',
    pwaPromptIOSDone: 'Potvrďte instalaci a je hotovo!',
    pwaPromptIOSOpenMenu: 'Otevřete menu prohlížeče',
    pwaPromptIOSParagraph: 'Abyste měli stopky uložené mezi aplikacemi a mohli je používat offline, je potřeba je nainstalovat:',
    pwaPromptIOSTitle: 'Nainstalujte si Debatní stopky',
    reset: 'Resetovat',
    resetConfirm: 'Opravdu si přejete stopky resetovat?',
    settings: 'Nastavení',
    start: 'Spustit',
    themeColour: 'Barevný režim',
    themeColourAuto: 'Auto',
    themeColourDark: 'Tmavý',
    themeColourLight: 'Světlý',
    title: 'Debatní stopky',
  },
  en: {
    about: 'Feel free to share any feedback or ideas at:',
    affirmative: 'Affirmative',
    cancel: 'Cancel',
    close: 'Close',
    debatiadaA1ClosingLabel: 'A1 Closing',
    format: 'Debate format',
    formatChangeConfirm: 'Changing the format resets the timer. Continue?',
    formatDebatiada: 'Debatiáda',
    formatKpdp: 'KPDP',
    language: 'Language',
    languageCs: 'Čeština',
    languageEn: 'English',
    linearFeatureDiscoveryButton: 'Tap the card at the start and end of each speech',
    linearFeatureDiscoverySettings: 'You can change the layout in Settings',
    linearPrepTimeSuffix: ' - prep time',
    mode: 'Display mode',
    modeClassic: 'Classic',
    modeLinear: 'Linear',
    negative: 'Negative',
    ok: 'OK',
    pause: 'Pause',
    preptime: 'Prep time',
    pwaPromptIOSAddToHomescreen: 'Select "Add to Home Screen"',
    pwaPromptIOSDone: 'Confirm the installation and you\'re done!',
    pwaPromptIOSOpenMenu: 'Open the browser menu',
    pwaPromptIOSParagraph: 'To keep the timer saved between launches and use it offline, install it:',
    pwaPromptIOSTitle: 'Install Debate Timer',
    reset: 'Reset',
    resetConfirm: 'Are you sure you want to reset the timer?',
    settings: 'Settings',
    start: 'Start',
    themeColour: 'Color theme',
    themeColourAuto: 'Auto',
    themeColourDark: 'Dark',
    themeColourLight: 'Light',
    title: 'Debate Timer',
  },
};

const getLocalisation = (
  language: Language = getActiveLanguage(),
): Record<string, string> => translations[language];

export default getLocalisation;
